baseURL = 'https://kulewicz.net'
languageCode = 'en-us'
title = 'kulewicz.net'
[params]
  description = "Automatyzacja, programowanie, cybersecurity"
  og_image = "/images/og_image.png"
[markup]
  [markup.highlight]
    style = 'catppuccin-frappe'
   
